
vision: >
  We want a society built on the principles of social justice and ecological and environmental sustainability, promoting education, curiosity and happiness.
    
  With this in mind, we produce and transmit fundamental and applied knowledge in agronomy, ecology and plant physiology. 

mission: >
  
  In PEPA, we are committed to building a society founded on the principles of social justice and ecological sustainability. Our mission is structured around three core pillars:

  ## Include

  - **Social Aspect:** We prioritize human inclusivity and fulfillment, ensuring that our research and initiatives are accessible and beneficial to all members of society.

  - **Professional Aspect:** We embrace transdisciplinarity and open our research to society, practical applications, fieldwork, greenhouses, and participatory research to foster a collaborative and inclusive environment.

  ## Innovate

  - We are dedicated to advancing knowledge and understanding through fundamental and applied research in agronomy, ecology, and plant physiology.

  - Our focus is on developing innovative methods, tools, and solutions to promote sustainable food and forest systems at various scales.

  ## Share

  - We are committed to training the next generation of researchers, equipping them with the skills and knowledge to drive future innovations.

  - We believe in open communication, sharing our findings "as much as needed, as little as possible," and promoting open-source practices.
  
  - We encourage and accept critical thinking, fostering an environment where diverse perspectives and collaborative efforts can thrive.

  Through these missions, we aim to create a positive impact on society and the environment, promoting education, curiosity, and happiness.


values: >


  Beyond research, we care<br>

  ## Active Care
  
  - **Justice:** We are committed to fairness and equity in all our actions and decisions.
  
  - **Respect:** We value and respect every individual, recognizing the inherent worth and dignity of all people.
  
  - **Kindness:** We approach our work and interactions with compassion and empathy.
  
  - **Sustainability:** We strive to ensure the sustainability of life, society, and our activities for future generations.
  
  - **Cooperation and Support:** We believe in the power of collaboration and mutual support to achieve common goals.
  
  - **Equity:** We are dedicated to promoting equity and inclusivity, embracing diverse people, worldviews, and beliefs.
  
  - **Receptiveness and Empathy:** We foster an environment of openness and understanding, valuing the perspectives and experiences of others.

  ## Openness
  
  - **Quality:** We are committed to excellence in all aspects of our work, striving for the highest standards of quality.
  
  
  - **Open World, Science, and Society:** We believe in the importance of openness in science and society, promoting transparency and accessibility.
  
  - **Creativity:** We encourage creativity and innovation, valuing new ideas and approaches.
  
  - **Knowledge:** We are dedicated to the creation, sharing, and critical evaluation of knowledge, fostering a culture of continuous learning and improvement.

  ## Engagement

  
  - **Drive:** We are passionate about our mission and committed to making a positive impact in the world.
  
  - **Community Involvement:** We actively engage with our communities, ensuring that our research addresses real-world issues and benefits society.
  
  - **Advocacy:** We advocate for social justice, ecological sustainability, and the well-being of all individuals and communities.
